### ISSUE TITLE
Inconsistent handling of `Accept` header across `api-snippets`, `sdk-standard-components` and `openapi-backend`

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2311]
**Summary**:
I've been testing the end to end transfer flows, and I'm running into issues with the `PUT /thirdpartyRequests/transactions/{id}` requests.

For example, sending a  `PUT /thirdpartyRequests/transactions/{id}` to the thirdparty-api-adapter:

```bash
curl -v -X PUT localhost:12000/thirdpartyRequests/transactions/02e28448-3c05-4059-b5f7-d518d0a2d8ea \
  -H 'Accept:' \
  -H 'Content-Type: application/vnd.interoperability.thirdparty+json;version=1.0' \
  -H 'FSPIOP-Source: dfspa' \
  -H 'FSPIOP-Destination: pineapplepay' \
  -H 'Date: 2021-01-01'\
  -d '{
    "transactionId": "e1a60f05-1c1b-4d9f-bcd9-3822ebad29d5",
    "transactionRequestState": "RECEIVED"
  }'
```

returns a `400 Bad Request`:
```
{"errorInformation":{"errorCode":"3102","errorDescription":"Missing mandatory element - /header must have required property 'accept'"}}

```

In our API-snippets definitions, we have the following entry:
```yaml
    Accept:
      name: Accept
      in: header
      required: true
      schema:
        type: string
      description: >-
        The `Accept` header field indicates the version of the API the client
        would like the server to use.
```
which tells `openapi-backend` to reject requests that don't have an `Accept` header.

In sdk-standard-components, the `Accept` header is not added for a `PUT` request: https://github.com/mojaloop/sdk-standard-components/blob/cd667c2f45935444e743c5f3c97e40bbae295d17/src/lib/requests/baseRequests.js#L367, I'm not exactly sure why this is the case - perhaps something to do with previous assumptions about PUT requests?

```js
// dont add accept header to PUT requests
if(method.toUpperCase() !== 'PUT') {
  headers['accept'] = `application/vnd.interoperability.${resourceType}+json;version=${this.resourceVersions[resourceType].acceptVersion}`;
}
```

So I see a couple options ahead of us:

1. Add the `Accept` header to the `PUT` case in sdk-standard-components
2. Change api-snippets to not require the `Accept` header

**Severity**: High - this is blocking e2e transfer linking work

**Priority**: Medium

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened:
- Priority when opened:
