### ISSUE TITLE
Firstname, Middlename and Lastname regex not supporting myanmar script unicode strings

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2358]
**Summary**:
Firstname, Middlename and Lastname regex not supporting myanmar script unicode strings

Issue moved from here: https://github.com/mojaloop/account-lookup-service/issues/420

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**

**Steps to Reproduce**
  1.
  2.
  3.

**Specifications**
  - Component (if known): ALS, quotes
  - Version: 
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @bushjames 

**Notes**:

The regex used for validating Firstname, Middlename and Lastname of parties is failing to match myanmar script unicode strings.

The regex specified e.g. here: https://github.com/mojaloop/account-lookup-service/blob/master/src/interface/api-swagger.yaml#L1233 fails to match strings such as "ကောင်းထက်စံ"

Analysis e.g. here: https://www.fontspace.com/unicode/analyzer#e=4YCA4YCx4YCs4YCE4YC64YC44YCR4YCA4YC64YCF4YC2

...shows this string to consist of valid unicode points in the "myanmar" script. I believe this, and similar strings should be permitted as name elements within party objects in API elements.

- Severity when opened:
- Priority when opened:

**Comment by mdebarros** [comment]
> It would seem that we are missing a `unicode category`.
> 
> The current regex:
> 
> ```
>       pattern: '^(?!\s*$)[\p{L}\p{Nd} .,''-]{1,128}$'
> ```
> 
> Would need to change to:
> 
> ```
>       pattern: '^(?!\s*$)[\p{L}\p{M}\p{Nd} .,''-]{1,128}$'
> ```
> 
> This includes the additional `unicode group`:
> `\p{M} or \p{Mark}: a character intended to be combined with another character (e.g. accents, umlauts, enclosing boxes, etc.).`

Reference: https://unicode.org/reports/tr18/#General_Category_Property

**Comment by mdebarros** [comment]
> > It would seem that we are missing a `unicode category`.
> > The current regex:
> > ```
> >       pattern: '^(?!\s*$)[\p{L}\p{Nd} .,''-]{1,128}$'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Would need to change to:
> > ```
> >       pattern: '^(?!\s*$)[\p{L}\p{M}\p{Nd} .,''-]{1,128}$'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This includes the additional `unicode group`:
> > `\p{M} or \p{Mark}: a character intended to be combined with another character (e.g. accents, umlauts, enclosing boxes, etc.).`
> 
> Reference: https://unicode.org/reports/tr18/#General_Category_Property

Going back to the Mojaloop Specification definition for the [MiddleName](https://github.com/mojaloop/mojaloop-specification/blob/master/fspiop-api/documents/v1.1-document-set/fspiop-v1.1-openapi3.yaml#L2347):

```yaml
    MiddleName:
      title: MiddleName
      type: string
      minLength: 1
      maxLength: 128
      pattern: ^(?!\s*$)[\w .,'-]{1,128}$
      description: Middle name of the Party (Name Type).
```

Matching the definition of the `\w` as per https://unicode.org/reports/tr18/#word

| Property | Standard | 
| --- | --- | 
| \w | \p{alpha} <br/>\p{gc=Mark} <br/>\p{digit} <br/>\p{gc=Connector_Punctuation} <br/>\p{Join_Control} |

Based on this definition we can substitute the `\w` standard definition to match EMACScript standard as follows:

| Standard | EMACScript | 
| --- | --- | 
| \p{alpha} | \p{L} |
| \p{gc=Mark} | \\p{gc=Mark} |
| \p{digit} | \p{digit} |
| \p{gc=Connector_Punctuation} | \p{gc=Connector_Punctuation} |
| \p{Join_Control} | \p{Join_Control} |

We can translate that into the following definition: 

```yaml
    MiddleName:
      title: MiddleName
      maxLength: 128
      minLength: 1
      pattern: '^(?!\s*$)[\p{L}\p{gc=Mark}\p{digit}\p{gc=Connector_Punctuation}\p{Join_Control} .,''-]{1,128}$'
      type: string
      description: Middle name of the Party (Name Type).
```

**Comment by mdebarros** [comment]
if we consider the [Mojaloop Specification](https://github.com/mojaloop/mojaloop-specification/blob/master/fspiop-api/documents/v1.1-document-set/fspiop-v1.1-openapi3.yam), refering to the [MiddleName#L2347](https://github.com/mojaloop/mojaloop-specification/blob/master/fspiop-api/documents/v1.1-document-set/fspiop-v1.1-openapi3.yaml#L2347) as an example:

```yaml
    MiddleName:
      title: MiddleName
      type: string
      minLength: 1
      maxLength: 128
      pattern: ^(?!\s*$)[\w .,'-]{1,128}$
      description: Middle name of the Party (Name Type).
```

We see that the `\w` is used to handle all Unicode characters. If we reference the Unicode specification for [\w](https://unicode.org/reports/tr18/#word) as follows:

| Property | Standard |
| --- | --- |
| word (\w) | \p{alpha} <br/>\p{gc=Mark} <br/>\p{digit} <br/>\p{gc=Connector_Punctuation} <br/>\p{Join_Control} |

We can map the standard definition for [\w](https://unicode.org/reports/tr18/#word) to [ECMAScript](https://262.ecma-international.org/9.0/#sec-runtime-semantics-unicodematchproperty-p) regex as follows:

| Standard | ECMAScript |
| --- | --- |
| \p{alpha} | |
| \p{gc=Mark} | |
| \p{digit} | |
| \p{gc=Connector_Punctuation} | |
| \p{Join_Control} | |

We can then substitute the [current implementation swaggers regex](https://github.com/mojaloop/mojaloop-specification/blob/master/fspiop-api/documents/v1.1-document-set/fspiop-v1.1-openapi3.yaml#L2347) as follows:

```yaml
    MiddleName:
      title: MiddleName
      maxLength: 128
      minLength: 1
      pattern: '^(?!\s*$)[\p{L}\p{gc=Mark}\p{digit}\p{gc=Connector_Punctuation}\p{Join_Control} .,''-]{1,128}$'
      type: string
      description: Middle name of the Party (Name Type).
```

This will result in [ECMAScript](https://262.ecma-international.org/9.0/#sec-runtime-semantics-unicodematchproperty-p) regex matches being identical to the official Unicode standard for [\w](https://unicode.org/reports/tr18/#word).
