### ISSUE TITLE
[charts] - kratos fails to deploy with older image 

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2578]
**Summary**:
In the mojaloop/charts repo, I wasn't able to get the `kratos` dependency working, because we use an older image tag:

https://github.com/mojaloop/charts/blob/master/mojaloop/example-backend/values.yaml#L2982
```
## Overriding the image to older one because of some schema changes not compatible with kratios UI 
## This can be reverted when we upgrade the kratos-ui according to the new 
image:
  repository: oryd/kratos
  tag: v0.5.5-alpha.1
```

When this image tag is resolved to the `kratos-courier-0 ` statefulset, the container fails to launch with the following error:

```
Error: unknown command "courier" for "kratos"
Run 'kratos --help' for usage.
unknown command "courier" for "kratos"
```

I suspect that by overriding the image above, we are breaking the chart elsewhere.

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**

**Steps to Reproduce**
  1.
  2.
  3.

**Specifications**
  - Component (if known): mojaloop/charts
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened:
- Priority when opened:
